multi-level main nav
* change main menu to 'All Links'
* not using smartmenu but an own, more bootstrap-like implementation
* submenu heading pages/entries work like 1st-level heading pages, which
means that they only act as togglers and cannot be accessed

My general recommendation: for heading pages use 'External Link' menu
entries with a non-existing anchor id, like #heading-page
Exception: with Multi-Language Manager, we need regular pages because
MLM cannot translate external link titles